module.exports = {
  content: [
    "./contato.html",
    "./curso.html",
    "./serviços.html",
    "./treinamento.html",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "tertiary-container": "#b0ae7c",
        "surface-container-low": "#f4f4ed",
        "inverse-primary": "#c1cba8",
        "surface-tint": "#596246",
        "on-tertiary-fixed": "#1d1d00",
        "secondary-container": "#cee9a1",
        "on-secondary-container": "#536a30",
        "surface-dim": "#dadad4",
        "outline-variant": "#c7c7bc",
        "on-surface-variant": "#46483f",
        background: "#fafaf3",
        "on-primary-fixed-variant": "#414a30",
        "primary-fixed-dim": "#c1cba8",
        "on-secondary": "#ffffff",
        tertiary: "#626035",
        "surface-container-high": "#e8e9e2",
        "on-primary-fixed": "#171e08",
        "surface-container-lowest": "#ffffff",
        secondary: "#4f652c",
        outline: "#76786e",
        "primary-container": "#293119",
        "on-error-container": "#93000a",
        surface: "#fafaf3",
        "on-tertiary-container": "#42411a",
        "on-secondary-fixed-variant": "#384d16",
        error: "#ba1a1a",
        "tertiary-fixed": "#e8e5af",
        "on-surface": "#1a1c18",
        "error-container": "#ffdad6",
        "on-tertiary": "#ffffff",
        "tertiary-fixed-dim": "#ccc995",
        "on-error": "#ffffff",
        "secondary-fixed-dim": "#b5d08a",
        "surface-bright": "#fafaf3",
        "on-tertiary-fixed-variant": "#4a4820",
        "on-primary": "#ffffff",
        "on-secondary-fixed": "#121f00",
        "secondary-fixed": "#d1eca4",
        "surface-container": "#eeeee7",
        "on-background": "#1a1c18",
        "surface-container-highest": "#e3e3dc",
        primary: "#151c06",
        "on-primary-container": "#909a7a",
        "inverse-on-surface": "#f1f1ea",
        "primary-fixed": "#dde7c3",
        "inverse-surface": "#2f312d",
        "surface-variant": "#e3e3dc",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "space-xl": "2.5rem",
        "space-2xl": "4rem",
        gutter: "1.5rem",
        "space-xs": "0.25rem",
        "margin-mobile": "1.25rem",
        "space-3xl": "6rem",
        "gutter-mobile": "1rem",
        "space-lg": "1.5rem",
        "space-sm": "0.5rem",
        "space-md": "1rem",
        margin: "3rem",
      },
      fontFamily: {
        "headline-md": ['"Exo 2"'],
        "body-md": ["Libre Franklin"],
        "display-mobile": ['"Exo 2"'],
        "label-eyebrow": ["Libre Franklin"],
        "headline-sm": ['"Exo 2"'],
        "label-button": ["Libre Franklin"],
        display: ['"Exo 2"'],
        "body-sm": ["Libre Franklin"],
        "headline-lg": ['"Exo 2"'],
        "headline-lg-mobile": ['"Exo 2"'],
        "badge-seal": ['"Exo 2"'],
        "body-lg": ["Libre Franklin"],
      },
      fontSize: {
        "headline-md": ["28px", { lineHeight: "34px", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "26px", fontWeight: "400" }],
        "display-mobile": [
          "38px",
          { lineHeight: "42px", letterSpacing: "-0.01em", fontWeight: "700" },
        ],
        "label-eyebrow": [
          "12px",
          { lineHeight: "16px", letterSpacing: "0.10em", fontWeight: "600" },
        ],
        "headline-sm": ["20px", { lineHeight: "26px", fontWeight: "600" }],
        "label-button": [
          "15px",
          { lineHeight: "20px", letterSpacing: "0.02em", fontWeight: "500" },
        ],
        display: [
          "56px",
          { lineHeight: "60px", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "body-sm": ["14px", { lineHeight: "22px", fontWeight: "400" }],
        "headline-lg": [
          "40px",
          { lineHeight: "46px", letterSpacing: "-0.015em", fontWeight: "600" },
        ],
        "headline-lg-mobile": [
          "28px",
          { lineHeight: "34px", letterSpacing: "-0.01em", fontWeight: "600" },
        ],
        "badge-seal": [
          "13px",
          { lineHeight: "16px", letterSpacing: "0.04em", fontWeight: "600" },
        ],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "300" }],
      },
    },
  },
};
